Repository eventespresso/eea-wpuser-integration, pull requests merged in 2020-12, with the labels that each got.

#25 Add GitHub actions PR check workflow
  .github/workflows/pr-check.yml
  .travis.yml
  composer.lock
  eea-wpuser-integration.php
  templates/content-espresso_my_events-simple_list_table.template.php
  templates/loop-espresso_my_events-event_section.template.php
  templates/loop-espresso_my_events-simple_list_table.template.php
  templates/status-legend-espresso_my_events.template.php
Labels: type:build-process 🔨

#26 Add ticket capability required to GQL schema
  domain/services/graphql/RegisterSchema.php
  eea-wpuser-integration.php
Labels: category:models-and-data-infrastructure, type:enhancement 🎉

#27 Prep for EDTR Integration
  EE_WPUsers.class.php
  domain/Domain.php
  domain/entities/routing/EspressoEventEditor.php
  domain/entities/routing/GQLRequests.php
  domain/services/assets/EventEditorAssetManager.php
  domain/services/graphql/RegisterSchema.php
  eea-wpuser-integration.php
Labels: category:core-plugin, status:review, type:enhancement 🎉

#29 Add WP User DOM Data for EDTR
  EE_WPUsers.class.php
  domain/entities/routing/EspressoEventEditor.php
  domain/entities/routing/GQLRequests.php
  domain/entities/routing/WpUserData.php
  eea-wpuser-integration.php
Labels: category:models-and-data-infrastructure, status:review, type:enhancement 🎉

#31 Deploy assets workflow
  .github/workflows/deploy-to-barista.yml
  .github/workflows/deploy-to-rc.yml
  assets/css/eea-wp-users-integration-spco.css
  assets/css/ees-espresso-my-events.css
  assets/images/spinner-2x.gif
  assets/images/spinner.gif
  assets/js/eea-wp-users-integration-spco.js
  assets/js/ees-espresso-my-events.js
  assets/src/.gitignore
Labels: type:build-process 🔨, type:task ✅
